### PR TITLE
Add customer reviews

### PR DESCRIPTION
**Pull request by suthargk**
Hey, I'm adding customer review component

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Screenshot 2020-10-18 at 12 33 54 PM
Screenshot 2020-10-18 at 12 37 46 PM

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Comment by tnylea** [comment]
Dude! This looks rad 👍 Thanks for the PR, merging it in ;)

**Comment by thinkverse** [comment]
The component has been moved into the `/components` folder and naming has been fixed so it will now be displayed on Tails.

**Comment by suthargk** [comment]
> The component has been moved into the `/components` folder and naming has been fixed so it will now be displayed on Tails.



> The component has been moved into the `/components` folder and naming has been fixed so it will now be displayed on Tails.

😢Sorry! I mistakenly put customer_reviews.html in root directory tails and put underscore instead of hyphen.

**Comment by suthargk** [comment]
> The component has been moved into the `/components` folder and naming has been fixed so it will now be displayed on Tails.

😢Sorry! I mistakenly put customer_reviews.html in root directory tails and put underscore instead of hyphen.

**Comment by suthargk** [comment]
> Dude! This looks rad 👍 Thanks for the PR, merging it in ;)

@tnylea  Thanks! I'll give 100% contribute to tails 😊. You can check my another components which are pretty awesome.

**Comment by suthargk** [comment]
@tnylea @thinkverse why this PR isn't labelled?

**Comment by thinkverse** [comment]
It's merged, so it shouldn't matter if it's not labeled. If you're talking about Hacktoberfest that is.

**Comment by suthargk** [comment]
> It's merged, so it shouldn't matter if it's not labeled. If you're talking about Hacktoberfest that is.

alright

**Pull request merged**
