### PR TITLE
added four section components

### PR DESCRIPTION
**Pull request by ghazimuharam**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🚩 Other

## Description
Four section using tailwindcss for hacktoberfest

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
image

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Comment by ghazimuharam** [comment]
I've updated the image

**Comment by ghazimuharam** [comment]
Hello there, Thank's for merging my pull request, since I've joined hacktoberfest event, can you add this pull request to hacktoberfest-accepted?

**Comment by thinkverse** [comment]
Shouldn't be needed since it's merged, but we can add it anyway. 👍

**Comment by ghazimuharam** [comment]
Thank you very much

**Pull request merged**
