### PR TITLE
Adding new animal-down component

### PR DESCRIPTION
**Pull request by ahhzaky**
Hey There,

I am adding a new component called animal-down

### CODE REVIEW

**Comment by kamerat** [comment]
It would be nice if you provided a image in the description. Good work 💯

**Comment by ahhzaky** [comment]
Can it be merged? or where should I make a description if needed?

**Comment by kamerat** [comment]
I am not a maintainer of this repository, so I cannot do so. I commented this because it will make it easier for the maintainers to see what you made and then read the code instead of having to download your version, build it and all in order to see what this is. If I was the maintainer, I would prioritize the PRs that made my life easier. _good description with images_

> where should I make a description if needed?

You can click the three dots at the right corner of the initial comment here, the one that says "Hey There, ..."
Then click `Edit`. When you are editing, you can drag in a image/screenshot of the component and Github will automagically upload and insert it in the post.

**Comment by ahhzaky** [comment]
Ooh thanks about that. I am still new to using Github so thank you for the advice.

**Comment by thinkverse** [comment]
This PR will sadly not be merged. The card component is generic and already exists on our platform and on many others. Hope you can understand. 🙂

**Pull request closed without merging**
