### PR TITLE
Add theme switcher button

### PR DESCRIPTION
**Pull request by crisgarlez**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

This PR add a theme switcher button with a header menu for an illustrative example, additionally add AlpineJS show/hide interaction

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Captura5

Captura6

## Added to documentation?

- [ ] 📜 readme
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by thinkverse** [comment]
Personally don't see the use for this particular component? If it's a single toggle, why does it have the header included? We already have a pretty full header component already. 🤔

**Comment by crisgarlez** [comment]
It is a button that I used on my personal website, I thought that if it was useful to me, it could be useful for someone else.

Captura9

**Comment by crisgarlez** [comment]
> Personally don't see the use for this particular component? If it's a single toggle, why does it have the header included? We already have a pretty full header component already. 🤔

Including the header was to better illustrate the example, to make it more realistic. I could remove it anyway

**Comment by thinkverse** [comment]
Cool, I get it. If you could fix the filename, and switch it from regular JS to AlpineJS I'll get this merged. 🙂

**Comment by thinkverse** [comment]
Sadly we regret to inform you that due to a change in direction, the PR  you've submitted will not be merged.
For more information about the upcoming changes, I refer you to the notice on our [README](https://github.com/thedevdojo/tails/blob/HEAD/README.md). 🙂

**Pull request closed without merging**
