### PR TITLE
New Hero Component Delivery

### PR DESCRIPTION
**Pull request by remizmohammed**
Hey guys,

I am adding a new Hero component Delivery.

Thanks.

### CODE REVIEW

**Comment by tnylea** [comment]
Cool 👍 

Can you make the mobile responsive style look a little better and I can get this merged in. Thanks.

Screen Shot 2020-10-01 at 11 00 55 AM

**Comment by remizmohammed** [comment]
Fixed responsive issue and pushed.👍

image

**Comment by remizmohammed** [comment]
Thankyou for your email

Updated.

**Comment by thinkverse** [comment]
Fixed the mobile view and transition between viewpoints and merged it. 👍

Screen shot of hero delivery component

**Pull request merged**
