### PR TITLE
Adding new login page component 

### PR DESCRIPTION
**Pull request by Laukik-11**
heyy there,

I am adding a login page component

### CODE REVIEW

**Review by thinkverse — CHANGES_REQUESTED** [review]
This PR does not contain any TailwindCSS classes and contains too much HTML to be considered a component. I suggest you look at our existing components and their code and alter your component accordingly. Do note that we already have a simple login page component so you might want to do something more with this. 🙂

**Comment by Laukik-11** [comment]
hey,
Updated my file , now  changed this to a profile card component with tailwindCSS classes

**Comment by tnylea** [comment]
Please resubmit with the following code:

```
<div class="max-w-screen max-h-screen flex items-center justify-center bg-white w-full">
<div class="shadow-lg sm:flex w-full max-w-6xl rounded-lg overflow-hidden">
  <div class="w-full text-white bg-gray-400 bg-center bg-cover sm:w-2/5"
     style="background-image: url('https://images.unsplash.com/photo-1504985954001-5737b2af529e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2879&q=80" class="object-cover w-full h-full')">
    <div class="p-8">
    
    </div>
  </div>
  <div class="w-full bg-white sm:w-3/5">
    <div class="p-8">
        <h1 class="text-3xl font-black">SIGN UP</h1>
    <p class="mt-2 text-base leading-tight text-gray-600 mb-5">Create an account to join our awesome community</p>
    <form>
      <label for="username" class="text-xs text-gray-500">Username</label>
      <input id="username" class="block w-full pb-1 m-auto mb-6 text-gray-700 bg-transparent border-b border-gray-500" type="text"
         placeholder=""/>
      <label id="passowrd" class="text-xs text-gray-500">Password</label>
      <input id="password" class="block w-full pb-1 m-auto mb-6 bg-transparent border-b border-gray-500 text-grey-700"
         type="password"
         placeholder=""/>
      <input class="w-full pt-3 pb-3 text-white bg-indigo-500 rounded-lg shadow-lg cursor-pointer hover:bg-indigo-400 "
         type="submit" value="Create account">
    </form>
    <div class="mt-4 text-center">
      <p class="text-sm text-gray-600">Already have an account? <a href="#" class="font-bold text-indigo-500 no-underline hover:text-indigo-400">Sign in</a></p>
    </div>
    </div>
  </div>
</div> 
</div>
```

Add a few more cleanups with empty divs, and I can get this merged in.

Thanks.

Screen Shot 2020-10-01 at 4 05 07 PM

**Comment by Laukik-11** [comment]
hey,
review it now and merge it please

**Review by thinkverse — APPROVED** [review]

**Comment by Laukik-11** [comment]
please merge it and add hactober fest accepted tag with it
thanks

**Comment by tnylea** [comment]
Thanks! I've gone ahead and merged this in ;)

**Pull request merged**
