### PR TITLE
Adding Skeleton Component

### PR DESCRIPTION
**Pull request by PritishNagpal**
## What type of PR is this? (check all applicable)
Added a new Component

## Description
Created a skeleton component which appears on screen while the data is loaded. This is my first PR  :)

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
         -------------------------------             Mobile View         -------------------------------                    
Screenshot (65)

         -------------------------------             Desktop View         -------------------------------      
Screenshot (64)

## Added to documentation?

- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by PritishNagpal** [comment]
Hey guys this is my first PR. Tried something different please guide me if anything needs to be changed. Thank You

**Review by thinkverse — CHANGES_REQUESTED** [review]
This button seems to be a bit out-of-place and can be removed. Not sure you need all six of the skeletons though, one should be enough I think. The end-user will most likely have only a single skeleton in a loop anyway. 🤔

**Comment by PritishNagpal** [comment]
Okay will remove the button and extra skeletons. One more thing should I center the only skeleton ?

**Comment by PritishNagpal** [comment]
Please review this.

**Review by thinkverse — APPROVED** [review]
Looks good, I'll merge this in and add some changes to it later. 🙂

**Pull request merged**
