### PR TITLE
Changed font color and background design of heading in feature-content-brow…

### PR DESCRIPTION
**Pull request by rbirkaur23**
…ser.html

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Comment by thinkverse** [comment]
Thank you for this PR. If you could, could you explain a bit why you think this change is necessary? 🙂

**Comment by rbirkaur23** [comment]
@thinkverse  Sir, I changed font color in heading and added font background color to make the it more colorful and attractive.
Hope you will like this.
Thank you, Sir

**Comment by thinkverse** [comment]
We thank you for this PR. 👏

Sadly I don't think these changes fit with the style already set in the component. So unfortunately I'm going do deny this PR. I suggest submitting a newly created component made from scratch that has a more colorful style. 🙂

**Comment by rbirkaur23** [comment]
Sure, I will try to make a newly created component.🙂

**Pull request closed without merging**
