### PR TITLE
add contact split-form

### PR DESCRIPTION
**Pull request by akash2408**
Screenshot_2020-10-06 Screenshot

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
I just tested the component but it does not seem to display as expected:

image

Can you look into this?

Also please make sure to exclude the `html`, `body` and `head` tags from the component.

**Comment by akash2408** [comment]
now it is working correctly kindly inform me if any issue occurs

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
Looks good! Thank you for the changes, I think that it just needs a little bit of mobile love:

image

image

**Comment by akash2408** [comment]
Ohkk, i will do that

**Comment by thinkverse** [comment]
Sadly we regret to inform you that due to a change in direction, the PR  you've submitted will not be merged.
For more information about the upcoming changes, I refer you to the notice on our [README](https://github.com/thedevdojo/tails/blob/HEAD/README.md). 🙂

**Pull request closed without merging**
