### PR TITLE
Display packages or product information in Card format.

### PR DESCRIPTION
**Pull request by xpharsh**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Added a component file named card-package.html in component folder where you can find a ready to use Card based design which is suitable to display Product or related information. It's  Responsive, I have prepared it for Mobile as well as Desktop. We have also added a hover effect which gives it a bit nicer look.

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by suthargk** [comment]
@xpharsh It looks beautiful but some changes required, what do you think @tnylea @thinkverse ?

**Comment by xpharsh** [comment]
> @xpharsh It looks beautiful but some changes required, what do you think @tnylea @thinkverse ?

Hi @suthargk, thanks, you like the work. Can you please let me know what changes you like to see, I will be happy to update the code

**Comment by xpharsh** [comment]
@thinkverse is there any issue with my contribution ? Any reason my contribution still not been merged ?

**Comment by thinkverse** [comment]
Sadly we regret to inform you that due to a change in direction, the PR  you've submitted will not be merged.
For more information about the upcoming changes, I refer you to the notice on our [README](https://github.com/thedevdojo/tails/blob/HEAD/README.md). 🙂

**Pull request closed without merging**
