### PR TITLE
Floating message notification

### PR DESCRIPTION
**Pull request by ghazimuharam**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Floating chat notification components with ping animation

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Desktop
image

Mobile
image

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by thinkverse** [comment]
This PR will not be merged since the PR heading and content don't match.

**Comment by ghazimuharam** [comment]
Sorry, I've changed the PR title, can you review it again?

**Comment by thinkverse** [comment]
If you could rename the file to `alert-customer-chat.html` that would be lovely. 🙂

**Comment by ghazimuharam** [comment]
Alright, I've renamed it to alert-customer-chat.html

**Comment by thinkverse** [comment]
Merged and updated a bit, but it's now live. 🙂

Screen Shot 2020-10-21 at 6 15 11 PM

**Comment by ghazimuharam** [comment]
That's awesome, can't wait to submit more PR :smiley_cat:

**Pull request merged**
