### PR TITLE
check this out

### PR DESCRIPTION
**Pull request by shades-7**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Comment by thinkverse** [comment]
Thank you for contributing to Tails. I sadly don't think this is a component. This looks more like a template too me. 🤔&nbsp; I would suggest you continue working on it, and move it into `/templates` instead. What do you guys think @tnylea @bobbyiliev?

**Comment by shades-7** [comment]
Okay I will try to make more changes to it and will make a template. Thank
you

**Comment by suthargk** [comment]
Hindustani chokri

**Comment by tnylea** [comment]
Yep @thinkverse , I'll merge it in for now, but eventually will move it over to the templates :)

**Pull request merged**
