### PR TITLE
adding a pagination tailwind components

### PR DESCRIPTION
**Pull request by rcode321**
create tailwind pagination components

### CODE REVIEW

**Review by thinkverse — CHANGES_REQUESTED** [review]
I like it! 😀&nbsp; Although the filename could be changed to just `pagination.html` or another suffix than _tailwind_. Tails only include components and templates based on TailwindCSS so adding it as a suffix to the filename it just redundant IMHO. 🙂

**Comment by rcode321** [comment]
Thanks thinkverse. i change the name from pagination-tailwind, to just pagination.html 😄

**Comment by tnylea** [comment]
Beautiful 👌 

I'm going to get this merged in and then I was going to change the name to `pagination-clean.html`, this way it has a description name at the end as well.

**Comment by rcode321** [comment]
tnylea cool! thanks. is this count on hactoberfest PR challenge? or it should be credited exactly on october 1?

**Pull request merged**
