### PR TITLE
added 404_page_not_found component

### PR DESCRIPTION
**Pull request by ganapathi12**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
hey! there added 404 page not found component in tailwind css

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Comment by ganapathi12** [comment]
Hi there! I would like to contribute more to this repo! So if you merge this branch, I can create more interesting components, and please tell me the reason why it's still not being merged!

**Comment by ganapathi12** [comment]
hi there! could you atleast add label "hacktoberfest-accepted" label to my pr so that it is eligible for hacktoberfest! @thinkverse

**Comment by thinkverse** [comment]
Hello @ganapathi12, sorry for the late response. Hacktoberfest has had me busy with spam for a few days now.
I will look over your PR in a couple of minutes when I have the time. I hope you understand. 🙂

**Comment by ganapathi12** [comment]
Hi @thinkverse @gustsu @crisgarlez @tnylea , I've participated in hacktoberfest. If this is accepted for hacktoberfest, Please add hacktoberfest-accepted label to it as mentioned in new guidelines by digital ocean.

**Comment by thinkverse** [comment]
Merged and fix some responsive issues and changed the design a bit. 🙂&nbsp; Also an FYI, please don't tag people randomly and create issues to get our attention, we will get to issues and PR's when we have the time, hope you understand that. 👍

Screen shot of component

**Comment by ganapathi12** [comment]
> Merged and fix some responsive issues and changed the design a bit. 🙂  Also an FYI, please don't tag people randomly and create issues to get our attention, we will get to issues and PR's when we have the time, hope you understand that. 👍
> 
> Screen shot of component

i am sorry! i new to this and i learnt a lot from this event about hacktoberfest and open source contributions! thanks for guiding me and helping me!

**Pull request merged**
