### PR TITLE
Creating contact-form

### PR DESCRIPTION
**Pull request by KaranSinghBisht**
## What type of PR is this? 
- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🚩 Other
## Description
Hey! I have added a contact form component
- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
form1
form2

### CODE REVIEW

**Comment by KaranSinghBisht** [comment]
Sorry for the bad ss,
But i couldn't make the playground preview fullscreen in the devdojo site
Which I suggest should be a feature but anyway 😄

**Comment by HariAcidReign** [comment]
Hey, quick question... Where can I find images like that? (The one below the lorem text)

**Comment by KaranSinghBisht** [comment]
Hi Hari ! You can find svg/png of these images on undraw.co for free of use !

**Comment by KaranSinghBisht** [comment]
Added New Letter component 
Should I include in tittle

**Comment by thinkverse** [comment]
I'm closing this PR since it contains more that one component, I suggest you open new ones for each of them. It'll be easier for us to keep track of them that way. Hope you understand. 🙂

**Comment by KaranSinghBisht** [comment]
Can someone remove the invalid label which I asked to put, just read the hacktoberfest-guidelines
More than 2 pr of invalid can get me disqualified 

Though I asked for the label myself can someone please remove it

**Pull request closed without merging**
