### PR TITLE
Adding Featured content with tiled images

### PR DESCRIPTION
**Pull request by ThinkDevStudios**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Featured Content with Tiled Images on the right side

# Mobile & Desktop Screenshots/Recordings (if there are UI changes)
image
image
image

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Comment by tnylea** [comment]
This looks rad man!

Great job.

**Comment by tnylea** [comment]
@ThinkDevStudios Got that merged in and live on the site ;)

Let me know if you got the credit for Hacktoberfest.

Talk to you soon.

**Comment by thinkverse** [comment]
> credit for Hacktoberfest.

Does that start to count already? I know you could sign up, but it's still September. 🤔

**Comment by ThinkDevStudios** [comment]
Hi tnylea. Have not received the credits yet for Hacktoberfest. I did register though.
image

**Comment by ThinkDevStudios** [comment]
Hi tnylea. Have not received hacktoberfest pull request yet. Or do i need to submit another pull request =(?

**Pull request merged**
