### PR TITLE
feature Shopping Cart added

### PR DESCRIPTION
**Pull request by Priyanka11-dev**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
Thank you for this PR! Would you mind updating the inline styles with TailwindCSS classes instead?

Also it might need a little bit of mobile optimization:
image

Thank you!

**Comment by Priyanka11-dev** [comment]
Hi @bobbyiliev ,
Updated the file as per your comment.
Kindly have a look.
Thankyou!!

**Comment by Priyanka11-dev** [comment]
Hey @bobbyiliev,
Kindly have a look and let me knw if any changes required.
Thankyou!!

**Comment by bobbyiliev** [comment]
Hi @Priyanka11-dev thank you for the changes! I've noticed that a checkout component already exists, but as you've put a lot of effort into this I will mark the PR as `hacktoberfest-accepted` so it will count as a valid PR. Thank you and good luck.

**Comment by Priyanka11-dev** [comment]
@bobbyiliev,
Thanks a lot :)

**Pull request closed without merging**
