### PR TITLE
Adding a new hero component

### PR DESCRIPTION
**Pull request by ifeigen**
Hey there!

This is my first time using tailwindcss and i have created a hero for a shopping website. I hope you like it!

### CODE REVIEW

**Review by tnylea — CHANGES_REQUESTED** [review]
If you could make the buttons aligned correctly and add a larger image from https://unsplash.com, I can see about getting this one merged in :)

Thanks.

Here's a quick screenshot of the modifications.

modify

**Comment by ifeigen** [comment]
Hello,

Thank you for reviewing my Pull Request. I have implemented the requested changes such as :

1. Aligning the button correctly
2. Adding a larger image from unsplash.com

I hope this satisfy your request.

Have a good day!

**Comment by ifeigen** [comment]
@tnylea Kindly please review my new commit

**Comment by ifeigen** [comment]
@thinkverse can you please review my code?

**Comment by ifeigen** [comment]
Hello, it's been several days without any response. Can you kindly review my code please? @tnylea @thinkverse

**Comment by tnylea** [comment]
Thanks for your patience, I made a few small tweaks and merged this in 👍

**Pull request merged**
