### PR TITLE
Adding new Alert component

### LINKED ISSUE #8: Add Alerts Tailwind CSS Component
Hi there, 

It will be great to expand this awesome collection by adding an **Alerts Tailwind CSS component** similar to what Bootstrap offers:

https://getbootstrap.com/docs/4.5/components/alerts/

Hopefully, someone might be up for the challenge 🙌

### PR DESCRIPTION
**Pull request by imsaptarshi**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Responsive alert component.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Screenshot (168)
### Mobile
Screenshot (169)

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
First time in both Hacktoberfest and Tails

### CODE REVIEW

**Review by thinkverse — CHANGES_REQUESTED** [review]
Thank you for contributing to Tails. 😀&nbsp; 👍

I would keep the alerts uniform instead of having one side rounded and the other not.

FYI,  this won't count towards Hacktoberfest unless the request is added on October 1 or later.

**Comment by imsaptarshi** [comment]
> Thank you for contributing to Tails. 😀  👍
> 
> I would keep the alerts uniform instead of having one side rounded and the other not.
> 
> FYI, this won't count towards Hacktoberfest unless the request is added on October 1 or later.

Yep ! I would do the necessary changes and make it uniform!
BTW, according to the rules of Hacktoberfest 2020 .. it has already started as it is mentioned that at any timezone when it comes October its started.

**Comment by thinkverse** [comment]
> BTW, according to the rules of Hacktoberfest 2020 .. it has already started as it is mentioned that at any timezone when it comes October its started

So it's October for you now? Nice, good luck with Hacktoberfest 2020. 👍

**Comment by imsaptarshi** [comment]
Screenshot (170)
### Hope it now looks fine.

**Comment by imsaptarshi** [comment]
And can you please label this as hacktoberfest

**Comment by imsaptarshi** [comment]
Have you checked the changes?

**Comment by thinkverse** [comment]
I'm about to now, I'm quite busy since it's currently my birthday at the moment. 👍

**Comment by imsaptarshi** [comment]
Woaah! Happy Birthday Man! I'm Sooo sorryy to disturb you in this great time!

**Review by thinkverse — CHANGES_REQUESTED** [review]
Current changes look good to me. But you have some single quotes `'` instead of double `"` on some elements and, some extra whitespace in some classes you might wanna remove. 👌

**Comment by imsaptarshi** [comment]
> Current changes look good to me. But you have some single quotes `'` instead of double `"` on some elements and, some extra whitespace in some classes you might wanna remove. 👌

Done! If you find more just let me know...hope you'll not!

**Comment by imsaptarshi** [comment]
Now is it ready to be Merged?

**Review by thinkverse — APPROVED** [review]
LGTM. 👍

**Pull request merged**
