### PR TITLE
Added a responsive gallery component

### PR DESCRIPTION
**Pull request by aryanarayantiwari**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ✔] 🚩 Other

## Description
Added a new responsive gallery component in the components folder made in tailwind css.

## Related Tickets & Documents
https://larainfo.com/blogs/tailwind-css-simple-responsive-image-gallery-with-grid

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
https://larainfo.com/blogs/tailwind-css-simple-responsive-image-gallery-with-grid

## Added to documentation?

- [ ] 📜 readme
- [ ✔] 🙅 no documentation needed

### CODE REVIEW

**Review by thinkverse — COMMENTED** [review]
Unless you can provide proof that you have permission to submit this component from Larainfo to Tails, this PR will not be merged.

**Comment by aryanarayantiwari** [comment]
It is from one of their tutorials so I guess it valid for someone who has followed the tutorial to submit it. However there's no way for me to contact her directly to ask her about submitting it as a PR. Also her website clearly states 'You are free to use the code snippets for personal or commercial projects'. You can check for yourself here[https://larainfo.com/terms-of-use](url)

**Comment by thinkverse** [comment]
Then I would suggest reading the tutorial, use what's learned there, and make your own version instead of copying the tutorial outright. As it stands now, this PR will not be merged.

**Comment by aryanarayantiwari** [comment]
> Then I would suggest reading the tutorial, use what's learned there, and make your own version instead of copying the tutorial outright. As it stands now, this PR will not be merged.
As described in her website terms of use. I can use their snippet for any thing. I suggest you take a look and then decide finally - 'You are free to use the code snippets for personal or commercial projects'. You can check for yourself here https://larainfo.com/terms-of-use

**Pull request closed without merging**
