### PR TITLE
Added CheckOut Component

### PR DESCRIPTION
**Pull request by HimanshuChittora23908**
Dear Sir/Ma'am,

I have added a component named CheckOut for issue number #243 (Feature: Add Checkout page Tailwind CSS Component). It is completely responsive and working component code using tailwind.
Kindly have a look at it and if possible please accept the PR.

Thanks and Regard
Himanshu Chittora

### CODE REVIEW

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
Thank you for this PR! The component looks great! Can you just fix the formatting/spacing to 4 spaces as per the [contribution](https://github.com/thedevdojo/tails/blob/master/CONTRIBUTING.md) file? Thanks!

**Comment by HimanshuChittora23908** [comment]
Sure Sir I will do the required changes by today itself and send you the new PR.

**Comment by HimanshuChittora23908** [comment]
Sir fixed the indentation to 4 spaces. Kindly have a look to it.

**Review by bobbyiliev — APPROVED** [review]

**Comment by HimanshuChittora23908** [comment]
Will it not get hacktoberfest accepted label?

**Comment by bobbyiliev** [comment]
As long as the repo has `hacktoberfest` label and the PR is merged, the `hacktoberfest-accepted` is not needed. But I've added it anyway.

**Pull request merged**
