### PR TITLE
Adding new component called comment-thread

### PR DESCRIPTION
**Pull request by darshDM**
hello Everyone...!
here is my first PR adding a component called comment-thread
i am new so let me know for any corrections and suggestion are highly appreciated

### CODE REVIEW

**Comment by connecteev** [comment]
@darsh2122 thanks! Any chance you could attach some screenshots?

**Review by thinkverse — CHANGES_REQUESTED** [review]
I think this component could be simplified a lot by removing the header section and focusing only on the comment threads. Also, I'm personally not a big fan of the way replies look. I would suggest just keeping the replies indented instead of flipped, it just looks weird IMHO. 🙂

The buttons also seem a bit too big, and the reddish-pink color on one of them doesn't fit the overall button design and feels like a destructive action rather than liking the reply.

Would work a bit on the overall spacing as well. 👍

**Comment by darshDM** [comment]
Sorry for bad design i have updated as need , please let me know any other updation required as i am new to tailwindCss and also in open source.

**Comment by tnylea** [comment]
Looks good. Thanks for the PR, I've made a few more changes to it, and you should be able to see it live on the site ;)

Screen Shot 2020-10-01 at 10 53 32 AM


Thanks again.

**Comment by darshDM** [comment]
> Looks good. Thanks for the PR, I've made a few more changes to it, and you should be able to see it live on the site ;)
> 
> Screen Shot 2020-10-01 at 10 53 32 AM
> 
> Thanks again.

Damn! you really made that cool... i want to learn tailwindCSS like this

**Pull request merged**
