### PR TITLE
Adding new pricing component.

### PR DESCRIPTION
**Pull request by kubeden**
Hey There,

I am working on this! I am polishing some stuff and will submit!

Best,
Dennis

### CODE REVIEW

**Review by thinkverse — CHANGES_REQUESTED** [review]
The font awesome icons could be removed I think. Tails don't include any CSS libraries out-of-the-box and assumes that the end-user is using TailwindCSS so the font awesome icons would just be an extra element that's not doing anything.

I would also remove the weird scaling that happens on the hover, it distracting and a bit out-of-place. 🙂

**Comment by kubeden** [comment]
Hey there, thanks for the suggestions. On it!

**Comment by thinkverse** [comment]
The over effect might work on the container itself if it's smoother, but that coupled with the scale hover effect on the buttons is a bit much IMHO. Also, it's not consistent between the buttons which the first having no hover effect, and the rest does.

Screen shot of the hover effects

**Comment by kubeden** [comment]
Hey, I touched it a bit. Could you tell me what program you are using to create such gifs so I can show the update? Thanks!

**Comment by thinkverse** [comment]
I'm using [Gyazo], they have a gif program where you can capture small clips, then I download the `.gif` version and remove it from the site after. 🙂

[gyazo]: https://gyazo.com/

**Comment by kubeden** [comment]
Okay, removed the scaling for the middle table, as well as the buttons. However, I am still wondering if the middle scale should be a little bigger than the left and right. Let me know.
b8f8fc3a932bbadb4a568ae197b805c1

**Comment by thinkverse** [comment]
Sorry for the late reply. Yes, The middle one being bigger has become a standard pattern for such price displays.
Usually, it contains the current "_best price_", so that would be a good pattern to follow. 🙂

**Comment by tnylea** [comment]
I personally think the middle price should be a little larger. Tomorrow I was going to make a few tweaks to this and then merge it in ;)

**Comment by thinkverse** [comment]
Read the message on Discord, he’ll hold off until the 1st. 👍🙂

**Comment by tnylea** [comment]
@thinkverse perfect 👌 Thanks for letting me know 😉

**Comment by thinkverse** [comment]
Just saw on Twitter this won't count towards Hacktoberfest, only requests open on October 1 and after will count, sorry @ascii-naut

**Comment by kubeden** [comment]
Hey, no worries, thanks for letting me know. I will still post my updated version soon.

**Comment by kubeden** [comment]
Hey there, let me know what you think of the following design:

7c31444822bc3e97aca2d44ec902358f

I did not add different svgs because I couldn't find 100% free ones that could match the component.

**Comment by thinkverse** [comment]
ℹ️ &nbsp; Hacktoberfest label removed, this PR won't count towards it since it was requested before October 1. 👨‍🔧

**Comment by connecteev** [comment]
@thinkverse @tnylea @ascii-naut I love the mobile / tablet / web responsiveness of https://www.sendfox.com/pricing
Something for consideration

**Comment by tnylea** [comment]
@ascii-naut I can merge this in if you would like and I was going to add a few mods, or we can close it and you can open a new one to get credit for Hacktoberfest, let me know what you would like to do :)

**Comment by kubeden** [comment]
Hey, I would love to get a point. Creating a new one sounds great!

**Pull request closed without merging**
